name: Build and push Dockerhub
on:
#  release:
#    types: [created]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Verzeichnis, das das Dockerfile und andere Dateien enthält
          push: true
          tags: docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}/dein-image-name:${{ github.sha }}
