name: Build and push to Dockerhub
on:
  release:
    types:
      - created
jobs:
  test:
    name: Test getting Vars
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF:10}
          echo ${GITHUB_REF:11}
          echo ${GITHUB_SHA:0:7}

  docker:
    name: Docker build on ubuntu-latest with JDK 11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_CLITOKEN }}
          logout: true
#      - name: Prep Ant script # need?
#        env:
#          BRANCH: ${{ needs.workflowvars.outputs.branch }}
#          REVISION: ${{ needs.workflowvars.outputs.revision }}
#        run: |
#          sed -i -r 's/revision="[A-Za-z0-9._-]+"/revision="'$REVISION'"/;s/branch="[A-Za-z0-9._-]+"/branch="'$BRANCH'"/;s/status="[A-Za-z0-9._-]+"/status="release"/' ivy.xml
#          echo $?
      - name: Build and Push DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            PROJECT_VERSION=1.1.0-test-c
#            PROJECT_VERSION=${{ needs.workflowvars.outputs.version }}
#            PROJECT_VERSION=${{ github.ref_name }}
            ANT_ARGS=-Dbuildtype=stable -Dversion=1.1.0-test-c
#            ANT_ARGS=-Dbuildtype=stable -Dversion=${{ github.ref_name }}
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:1.1.0-test-c
#            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:${{ github.ref }}-c
#            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:${{ github.ref_name }}-c
            ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO_STABLE }}:latest